### ISSUE TITLE
Overriding the "legendItemFontSize" by CSS.

### ISSUE THREAD

**Issue by dalroy44** [fusioncharts/fusioncharts-dist#3]
As part of upgrade from 3.10.1 to 3.12.2 found some Legend font issues and provided JS Fiddle as a reference.
legendItemFontSize attribute is overridden if below CSS is defined as application level.

`body, text{
  font-size: 14px;
}`

Even if the above CSS is part of application along with 3.10.1. Chart legends are not overridden. But after upgrade to 3.12.2, observed the font issues.

Added both jsFiddle. 

jsFiddle (3.12.2 fusionchart): http://jsfiddle.net/PyroDox/80rvceLv/

jsFiddle(3.10.1 fusionchart): http://jsfiddle.net/PyroDox/k0nt8mca/1/

**Comment by srishti-fc** [comment]
We would suggest you to kindly upgrade to our latest version of FusionCharts (v3.16.0) by using our latest CDN link (https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js) in your application. The reported scenario has been fixed in our latest version.
Reference sample: http://jsfiddle.net/srishti_fc/wn3qfjp1/
