### ISSUE TITLE
How to make Timeline chart stretch 100%

### ISSUE THREAD

**Issue by aquaductape** [fusioncharts/fusioncharts-dist#9]
Is there a configuration to maximize the length of chart? I ask because there's at least 30 pixels of padding on the left and it takes up a lot of space on small devices, when I would like it be 0 and centered.
![Screenshot from 2019-10-28 16-19-39](https://user-images.githubusercontent.com/29286430/67725369-5dc7c400-f99f-11e9-98ac-0d842f766f49.png)

**Comment by soumyasdutta** [comment]
Hey,

Hope you have set the chart width as 100% 

yes if the y-axis title is also hidden there is some padding present for which we have already logged issue internally so that in the later version possibilities to perform canvas and chart margin and padding manipulation could be there.

We are keeping a note about it and when there is any update regarding the same we would update here.

**Comment by soumyasdutta** [comment]
Hi
Please check with the latest version of FusionTime i.e. 2.1.0 where according to the rule of proximity, the Y-axis title now appears closer to Y-axis labels. The default space between them has been reduced.
